export const DEFAULT_PAGE = 1
export const DEFAULT_ITEM_PER_PAGE = 5

export const PAYMENT_METHOD = {
  COD: 'COD',
  STRIPE: 'STRIPE'
}

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  UNPAID: 'UNPAID'
}

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
}
